debug: false
bpf:
  page_table_scale_factor_gb: 200
process_discovery:
  concurrency: 4
egress:
  interval: "1m"
storage:
  host: {{ include "perforator.storage.host" . }}
  tls:
    enabled: {{ .Values.agent.tls.enabled }}
    ca_file_path: {{ include "perforator.agent.tlsCACert" . }}
    certificate_file_path: {{ include "perforator.agent.tlsCert" . }}
    key_file_path: {{ include "perforator.agent.tlsCertKey" . }}
upload_scheduler:
  max_opened_binaries_queue: 20
  max_closed_binaries_queue: 1000
  max_simultaneous_uploads: 10
perf_events:
- type: CPUClock
  frequency: 99
pods_deploy_system:
  deploy_system: "kubernetes"
  kubernetes:
    topology_lable_key: {{ .Values.agent.config.topologyLableKey | quote }}
  pod_options:
    default: true